--Creating the base database, schema, and warehouse environment if they do not already exist
CREATE DATABASE IF NOT EXISTS DKU_DEMO;
CREATE SCHEMA IF NOT EXISTS DKU_DEMO.{{schema_name}};
USE SCHEMA DKU_DEMO.{{schema_name}};

CREATE WAREHOUSE IF NOT EXISTS XSMALL_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE XSMALL_WH;