name: base_env_setup

# Controls when the action will run. 
on:
  # push:
  #   branches:
  #     - dev
  #   paths:
  #     - 'base_setup/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  reset-snowflake-env:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Install dependencies
        run: pip install snowflake-connector-python

      - name: Execute base env creation python
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          # SF_ROLE: ${{ secrets.SF_ROLE }}
          # SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          # SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          # KAGGLE_USER: ${{ secrets.SF_KAGGLE_USER }}
          # KAGGLE_TOKEN: ${{ secrets.SF_KAGGLE_TOKEN }}
        run: python $GITHUB_WORKSPACE/utility/full_cleanup.py
