name: snowflake_flask_api_demo_dev_docker build and deploy

on:
  push:
    branches:
      - dev
      - flask_build
    paths:
      - 'src/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Snowflake Image Repository
      run: |
        docker login --username ${{ secrets.SF_USERNAME }} --password ${{ secrets.SF_PASSWORD}} ${{ secrets.SF_IMG_REPO }}.snowflakecomputing.com/api/public/api

    - name: Build the Docker image
      env:
        IMG_NAME: dataapi
      run: |
        docker build -t ${{ secrets.SF_IMG_REPO }}.snowflakecomputing.com/repo_name/$IMG_NAME:latest .

    - name: Push the Docker image
      env:
          IMG_NAME: dataapi
      run: |
        docker push ${{ secrets.SF_IMG_REPO }}.snowflakecomputing.com/repo_name/$IMG_NAME:latest